version: "3"
services:
  web:
    image: suren12/app_image
    ports:
      - "80:5000"
    container_name: web
    networks:
      - default
      - swole_net
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

networks:
   swole_net:
